version: '3.9'

services:
  server:
    build: .
    ports:
      - "3001:3000"
  db:
    image: "postgres"
    ports:
      - "27018:27017"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
